name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Run Tests
        run: python tests.py

      - name: Build macOS Application
        run: |
          # Build standalone executable with PyInstaller
          pyinstaller --onefile --windowed --icon=icon.icns --name "Secure Password Manager" main.py
          
          # Create app directory structure if needed
          mkdir -p "dist/Secure Password Manager.app/Contents/MacOS"
          mkdir -p "dist/Secure Password Manager.app/Contents/Resources"
          
          # Copy executable to app bundle if not already there
          if [ ! -f "dist/Secure Password Manager.app/Contents/MacOS/Secure Password Manager" ]; then
            cp "dist/Secure Password Manager" "dist/Secure Password Manager.app/Contents/MacOS/"
          fi
          
          # Copy icon if it exists
          if [ -f "icon.icns" ]; then
            cp "icon.icns" "dist/Secure Password Manager.app/Contents/Resources/"
          fi

      - name: Package as DMG
        run: |
          hdiutil create -volname "Secure Password Manager" -srcfolder "dist/Secure Password Manager.app" -ov -format UDZO "SecurePasswordManager.dmg"

      - name: Upload DMG to GitHub Releases
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          files: SecurePasswordManager.dmg
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v1.0.${{ github.run_number }}
          name: "Secure Password Manager v1.0.${{ github.run_number }}"
          body: "Automated release of Secure Password Manager"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}